FROM eclipse-temurin:21-jdk-jammy AS builder

WORKDIR /app

COPY . .

#RUN apt-get update && apt-get install -y dos2unix

#RUN dos2unix mvnw

RUN chmod +x mvnw && ./mvnw clean package -DskipTests

FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

CMD ["app.jar"]
