on:
  workflow_dispatch:




jobs:
  triger-composite-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: one
      - name: calling composite actions
        uses: ./.github/actions/setup-and-greet/

      - run: echo "Greeted Status= $greeted"
        shell : bash
        env: 
          greeted: $ {{steps.one.outputs.greeted}} 


