on:
  push:
    branches: [main]



jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6


      - name: docker login
        uses: actions/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: ./AI-BankApp-DevOps 
          file: ./AI-BankApp-DevOps/Dockerfile.multistage
          push: true
          tags: 
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ github.sha::7 }}
