name: environment variables
on:
  workflow_dispatch[[I

env:
  APP_NAME: myapp


jobs:
  print-env:
    env:
      ENVIRONMENT: staging


    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          echo "worfklow level: $APP_NAME"
          echo "Job level: $ENVIRONMENT"
          echo "Step level: $VERSION"

      env:
        VERSION: 1.0.0
