name: github-runners

on:
  workflow_dispatch:



jobs:
  ubuntu_runner:
    runs-on: ubuntu-latest
    steps:
      - name: print OS
        run: |
          echo "Runner OS is $RUNNER_OS"

      - name: Runner hostname
        run: |
          echo "Hostname: $(hostname)"

      - name: Current runner
        run: |
          echo "Current User: $USER"



  windows_runner:
    runs-on: windows-latest
    steps:
      - name: print OS
        run: |
            echo "Runner OS is $RUNNER_OS"
      - name: Runner hostname
        run: |
            echo "Hostname";hostname

      - name: Current user
        run: |
            echo "Current User";whoami


  macos_runner:
    runs-on: macos-latest
    steps: 
    - name: print OS
      run: |
            echo "RUNNER OS is $RUNNER_OS"

    - name: Runner hostname
      run: |
            echo "Hostname";hostname

    - name: Current user 
      run: |
            echo "Current User";whoami
