name: Github Hosted Runmers
on:
  workflow_dispatch:


jobs:
  github_runner:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Collect System Information
        uses: lexbritvin/os-info-action@v1
        id: sys-info

      - name: Print System Info 
        run: |
          echo ${{ steps.sys-info.outputs }}







