name: Hello-Workflow
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout

      - name: Greets
        run: echo "Hello From Github Actions"
