name: Hello Workflow
on:
  push:
    branches:
      - main




  jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: Code Checkout
          run: actions/checkout@v4


        - name: Prints Hello
          run: echo "Hello from GitHub Actions!"
