name: Job Output
on:
  push:
    branches: [main]


jobs:
  date-string:
    runs-on: ubuntu-latest
    steps:
      - name: date
    outputs:
      echo "date=$(date)" >> $GITHUB_OUTPUT

  print-date:
    runs-on: ubuntu-latest
    needs: date-string
    steps:
      - name: print date
        env:
          output: ${{ needs.date-string.outputs.date }}
        run: |
          echo "$output"


