on:
  workflow_dispatch:

    inputs:
      env:
        description: 'Environment name'
        required: true
        default: 'dev'
        type: text
        options:

  

jobs:
  env_gather:
    runs-on: ubuntu-latest

    steps:
      - name: print env
        run: |
          echo "The environment is : ${{ github.event.inputs.env }}"

