name: Matrix Workflow

on:
  push:
    branches: [main]



jobs:
  python_version_check:
    strategy:
      fail-fast: false
      matrix:
        python_versions: ['3.10','3.11','3.12']
    runs-on: ubuntu-latest

    steps:
      - name: install python version
        uses: actions/setup-python@v6
        with:
          python_version: ${{ matrix.verison }}

      - name: print python version
        run: python --verison


