name: Matrix Workflow

on:
  push:
    branches: [main]



jobs:
  python_version_check:
    strategy:
      fail-fast: false
      matrix:
        python_versions: ['3.10','3.11','3.12']
    runs-on: ubuntu-latest

    steps:
      - name: install python version
        run: pip install $ {{ matrix.python_versions}}

      - name: print python version
        run: python --verison


