name: PR-Check
on:
  pull_request: [main]


jobs:
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: file check 
        run: |
          for file in .
            do 
             if [ $(du -sh $file | awk '{print $1}'|cut -c1) -gt 1000 ] 
             then 
               echo "File is greater than 1 MB , please check"
               exit 1
             else
               echo " File check Passed"
             fi 
            done

  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: branch name check
        run: |
          branch_name=${{ github.head_ref }}
          feature/*, fix/*, or docs/*
          case "$branch_name" in
            feature/*)
              echo "Valid branch name"
            fix/*)
              echo "Valid branch name"
            docs/*)
              echo "Valid branch name"
            *)
              echo "Invalid branch name"

          esac

          
  pr-body-check:
    runs-on: ubuntu-latest
    steps:
      pr_body=${{ github.event.pull_request.body }}
      if [ -z $pr_body ]; then
        echo "Warning: Description is empty .....Proceeding"
      else
        echo "PR Description is not null"
      fi
  
