name: pr-check

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - updated



jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: PR Check
        run: echo "PR check running for branch:${{ github.ref_name }}"
        


