name: Secrets Access
on:
  workflow_dispatch



jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
      - name: read secret
        run: |
          if [ -n ${{ secrets.MY_SECRET_MESSAGE}} ]
          then
          echo "The secret is set: true"
          else
          echo "The Scret is not set"
          
      - name: print secret
        run:
          echo "Printing secret message"
          echo "$secrets.MY_SECRET_MESSAGE"
