name: Secrets As Environment VAR
on:
  workflow_dispatch



jobs:
  secrets-as-env:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}

    steps:
      - name: secret-check
        run: |
          if [ -z "$SUPER_SECRET" ]; then
            echo "Oops.....No Secrets available"
          else
            echo "Super Secret is set"
          fi


   

