name: Secrets Access
on:
  workflow_dispatch



jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
      - name: read secret
        run: |
          echo "The secret is set: true" && echo "$secrets.MY_SECRET_MESSAGE"
        with:
          SUPER_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
