on:
  push:
    branches:
      - main
      - 'release/*'

    paths-ignore:
      - '*.md'
      - 'docs/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: print message
        run: |
          echo "workflow triggered as push was not in docs and .md file"
